### ISSUE TITLE
Administration page not working

### ISSUE THREAD

**Issue by fishermans** [adhi-software/sidebar-white#9]
Cannot open any entry on Administration page on Redmine 5.1:

<img width="287" alt="image" src="https://github.com/user-attachments/assets/ba0f0eba-0204-4345-941c-8b27e348b437">

**Comment by Arun-TAK** [comment]
This issue is fixed in v1.1.1, please take a look.

**Comment by fishermans** [comment]
It's still the same. Last changed is in use:

<img width="994" alt="image" src="https://github.com/user-attachments/assets/cd9bd71b-3e06-42d4-90c4-de22f654d0c0">

**Comment by dhanasingh** [comment]
Can you try clearing the browser cache and see if it helps.

**Comment by fishermans** [comment]
It's come using Dev Mode having Caching disabled. Also, the loaded js is the desired version.

Just to make clear, how to reproduce:
- Open Administration (view looks ok so far)
- Select any item, e.g. Users (view looks like shown on the initial posted screenshot)
- Same behaviour when clicking on "My account"
- In small responsive view, all is fine

**Comment by Arun-TAK** [comment]
We have fixed the admin links issue. Please uncompress the attached file then replace theme.js file in the path "redmine\public\themes\sidebar-white\javascripts\"
[theme-js.zip](https://github.com/user-attachments/files/17038420/theme-js.zip)
[theme-js.zip](https://github.com/user-attachments/files/17038420/theme-js.zip)

**Comment by fishermans** [comment]
Thanks a lot. It's working now.

Just some adjustments regarding the paddings are needed.

````patch
Subject: [PATCH] Paddings fix: #9
---
Index: stylesheets/application.css
<+>UTF-8
===================================================================
diff --git a/stylesheets/application.css b/stylesheets/application.css
--- a/stylesheets/application.css	(revision 3369d52b1d3f9d94ce9b484a4b137c94ea0c9a14)
+++ b/stylesheets/application.css	(date 1726638285078)
@@ -494,11 +494,7 @@
 }
 
 #sidebar p,#sidebar ul, #sidebar h3, #sidebar h4, #sidebar div{
-  padding-left: 10px;
-}
-
-#admin-menu{
-  padding-left: 0px !important;
+  padding: 5px 0px 5px 20px;
 }
 
 #admin-menu ul{
@@ -1009,4 +1005,4 @@
 
 .gantt_subjects div > span.expander {
   padding-left: 17px;
-}
\ No newline at end of file
+}

````

**Comment by Arun-TAK** [comment]
Ok, thanks. We will put this fix and the padding fix in the next release.
